### PR TITLE
AQCU-808: Added functionality for estimated series to plot with gaps.

### PR DESCRIPTION
**Pull request by zmoore-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
pulling this locally to test out.

**Comment by mhines-usgs** [comment]
@zmoore-usgs what's a good example of testing here? Not seeing much of a difference in before/after with the one suggested by laura?  "the Location 01010000, Discharge, Jan to Aug 2015 for DV Hydro has estimates that should show, if that's useful."

**Comment by zmoore-usgs** [comment]
@mhines-usgs Yeah, that additional one from Laura didn't have multiple estimated periods so there wasn't much difference. Take a look at the third example she posted in the description:
"DV Hydro, Location 01643700, Discharge, Dec 2013 to Feb 2014"

**Comment by mhines-usgs** [comment]
thanks :)

**Pull request merged**
