### PR TITLE
fixing check problems

### PR DESCRIPTION
**Pull request by mhines-usgs**

### CODE REVIEW

**Comment by lindsayplatt** [comment]
wait...for reals....

**Comment by mhines-usgs** [comment]
@lindsaycarr i don't think these are showstoppers because they're not causing dysfunction, just found a bunch of problems in the check that are errors that probably should be addressed and could be why travis is sad

**Comment by dpattermann-usgs** [comment]
Didn't @zmoore-usgs remove the Pandoc/"html" options recently? Sorry if I'm out of the loop.

**Comment by zmoore-usgs** [comment]
Yeah, I removed those here: https://github.com/USGS-R/repgen/pull/485

**Comment by zmoore-usgs** [comment]
Whoops, meant to just click "comment" not "comment and close". Sorry! :slightly_frowning_face:

**Pull request closed without merging**
