### PR TITLE
AQCU-1144: Zack noticed the original implementation was shifting the …

### PR DESCRIPTION
**Pull request by mhines-usgs**
…start date; changing so it preserves the actual start date

### CODE REVIEW

**Review by zmoore-usgs — APPROVED** [review]
Looks good to me! Tested locally and it is working as expected.

**Comment by mhines-usgs** [comment]
:/ i don't see the issue in the travis build, does anyone else? @zmoore-usgs or @thongsav-usgs ?

**Comment by mhines-usgs** [comment]
@zmoore-usgs hopefully.. now.. it should be better and handle the missing startDate/endDate of DC :D

**Comment by zmoore-usgs** [comment]
Looks like it's all good now! Your added anyDataExist checks look good to me.

**Comment by mhines-usgs** [comment]
Cool, thanks!

**Pull request merged**
