### PR TITLE
AQCU-844: Temporary(?) fix for boxes rendering improperly with year 9999

### PR DESCRIPTION
**Pull request by zmoore-usgs**
Issue seems to be something within GSPLOT?

### CODE REVIEW

**Comment by mhines-usgs** [comment]
We came across this doing the corr report as well as in transitioning to the bars/rectangles for approvals. To "fix" we change the year if it was 9999 to 2100.

**Comment by zmoore-usgs** [comment]
@mhines-usgs Ah gotcha. For consistency purposes do you think it would be best to change my fix from changing "9999-xx-xx" to the plot max date + 1 day to just changing it to be year 2100?

**Comment by mhines-usgs** [comment]
I think your fix works just fine, but you might want to make a comment above it why it's there? so we can revisit it...

**Comment by mhines-usgs** [comment]
duh, you already did that ;)

**Comment by lindsayplatt** [comment]
We're trying to get away from the hard-coded date changes. I would suggest switching to the 2100 method. Use the function `toEndOfTime` for that https://github.com/USGS-R/repgen/blob/master/R/utils-time.R#L86

``` r
laneData$endDates <- toEndOfTime(addData$dateData$dateRange[2])
```

**Pull request merged**
