### PR TITLE
adding a 'legend' to the vdiagram report

### PR DESCRIPTION
**Pull request by mhines-usgs**
One thing I'm not sure about, is how to make sure the report stays on two pages. should I alter the margins in the yaml? Suggestions?

right now it pushes the heading/title onto a new page for the 2nd report, and then there is a page break before the rest of the report.

https://internal.cida.usgs.gov/jira/browse/AQCU-307

### CODE REVIEW

**Comment by mhines-usgs** [comment]
@jread-usgs could you gander at this?

**Comment by jordansread** [comment]
looks good - altering the margins in yaml and also the fig sizes would be a fix.

**Comment by mhines-usgs** [comment]
@jread-usgs OK, I wasn't sure if there was a better way. I'll go with that for now since that'll be easier than revising the entire layout.

**Comment by thongsav-usgs** [comment]
Note that I had trouble changing the margin in the yaml and had to do it in the Rmd. See https://github.com/USGS-R/repgen/blob/master/inst/uvhydrograph/uvhydrograph.Rmd

**Comment by mhines-usgs** [comment]
@thongsav-usgs thanks, I did see that. I will muck around..

**Comment by jordansread** [comment]
ok, margins in Rmd (until we figure out how to yaml them), but fig widths and heights in the yaml.

**Comment by mhines-usgs** [comment]
Glad you remarked that the yaml wasn't working for you, too @thongsav-usgs , I was banging my head against that this morning, change, refresh, rebuild, WHY?!

**Comment by jordansread** [comment]
@mhines-usgs is this good to go?

**Comment by mhines-usgs** [comment]
you can merge it, i will be pushing further tweaks someday when I can work
on it. :(

```

Megan K. Hines

Contractor, Cherokee Nation Technology Solutions
Center for Integrated Data Analytics
USGS Wisconsin Water Science Center
8505 Research Way
Middleton, WI 53562
Office: 608-821-3917
mhines@usgs.gov

On Mon, Jun 8, 2015 at 8:42 AM, Jordan S Read <notifications@github.com>
wrote:

> @mhines-usgs <https://github.com/mhines-usgs> is this good to go?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/repgen/pull/52#issuecomment-109999853>.
>
```

**Comment by jordansread** [comment]
cool. merging.

**Pull request merged**
