### PR TITLE
Aqcu 1196 updates - TSS UI Improvements to report width and sorting icon location

### PR DESCRIPTION
**Pull request by mhines-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
I'm not quite sure why the commits for AQCU-1199 are showing up here..

**Comment by zmoore-usgs** [comment]
Once the tickets for  AQCU-1199 are merged hopefully those commits will disappear from this PR. I'll pull this down and check it out after that.

Edit: Huh, looks like those other PRs were merged and those commits are still showing here. I don't think that will cause merge conflicts since the changes should be identical but you might want to try pulling master into this branch.

**Comment by mhines-usgs** [comment]
@zmoore-usgs thanks, I'll do that...

**Comment by mhines-usgs** [comment]
Woo, that did the trick.

**Comment by zmoore-usgs** [comment]
Pulling this down to test now

**Review by zmoore-usgs — APPROVED** [review]
Changes look good and it works well locally!

**Comment by mhines-usgs** [comment]
Thanks! I'll merge once Travis verifies :+1:

**Pull request merged**
