### PR TITLE
AQCU-994: Modified reading of SVP field visits to move associated IV …

### PR DESCRIPTION
**Pull request by zmoore-usgs**
…information to the highest-value reading per visit for visits that have mutliple readings.

### CODE REVIEW

**Comment by mhines-usgs** [comment]
@zmoore-usgs it looks like its reverse sorting (latest -> earliest) now, is that an oversight or you wanted that change?

image

**Comment by zmoore-usgs** [comment]
@mhines-usgs Woah, that's weird. I'm not seeing that locally. Could you send me the json you're using?

**Comment by mhines-usgs** [comment]
Looks like this now, seems correct? 
image

**Review by mhines-usgs — APPROVED** [review]
Seems to work correctly, and it looks like there was a test that caught the output incorrect? :+1:

**Comment by zmoore-usgs** [comment]
Yeah, there was already a test in-place testing the order of the rows, but it passed locally since I didn't have the newest version of dplyr.

**Pull request merged**
