### PR TITLE
Added rounding to account for border comparison on calculated number

### PR DESCRIPTION
**Pull request by thongsav-usgs**
ranges.

### CODE REVIEW

**Comment by thongsav-usgs** [comment]
@jiwalker-usgs and @lindsaycarr not a huge fan of this, but the other option was adding an error range to each calculation.

We were already using 2 as a known precision for these numbers (specified by the source) so I opted to just go with rounding as the quickest implementation.

**Comment by lindsayplatt** [comment]
@thongsav-usgs I like that you made that a function so it's very easy to change. Although this might be the answer to your problem: https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f

Use `all.equal()` and it has a built in tolerance. You can also adjust the tolerance using the `tolerance` argument

**Comment by thongsav-usgs** [comment]
I don't think that includes less than or equal, but we could do that in the boolean logic itself.

**Comment by lindsayplatt** [comment]
Could you do two separate statements?

```
if(x < y | all.equal(y,x)){
     #do something
}
```

**Comment by thongsav-usgs** [comment]
This conversation is bleeding into #240

**Pull request merged**
