### PR TITLE
wip for switching to new gsplot version

### PR DESCRIPTION
**Pull request by lindsayplatt**
Still need to address:
- [x] limits not correct - error_bars (uvhydro-example.json) and points are cut off (uvhydro-groundwater.json)
- [x] grid lines (UvSquishedGrids) & approval bars out of order (uvhydro-gw-readings-example.json)
- [x] data correction entries cut off (uvhydro=pH-example)
- [x] legend entries doubling again (UvError - June 2015)
- [x] temporary fix for `uvhplot$view$window$par` (why is par here?) 
  - occurs in `uvhydro-example.json`, `uvhydro-readings-example.json`
  - cex from the `meas_Q` callout is getting put here
  - seems to be a gsplot issue, not a repgen issue

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@mhines-usgs here's the work in progress for gpslot new version. Not ready to merge this, but you can pull it down from here if you would like

**Comment by mhines-usgs** [comment]
Once this is closed out I can make a PR for the commit I put in for reversing the axes.

**Comment by lindsayplatt** [comment]
I've got a couple more fixes that I'm working on today - I am hoping they will be done today

**Comment by lindsayplatt** [comment]
@mhines-usgs there's a temporary fix in for that last item. It's on the gsplot side, so we are working on it, but I know we need to get this moving. Let's just leave in that temporary fix until that little issue is fixed in gsplot?

**Comment by lindsayplatt** [comment]
also @mhines-usgs and @thongsav-usgs where do we need to go change all of the gsplot versions? It's not in the DESCRIPTION file like I thought. We need gsplot v0.4.2 now

**Comment by lindsayplatt** [comment]
Don't merge this yet!!! I've actually got one more thing to work out, plus the gsplot fix for cex will be done momentarily

**Comment by thongsav-usgs** [comment]
Please add the explicit version to the description. Beyond that we'll update our deployer to push the right version to the servers.

**Pull request merged**
