### PR TITLE
Fixing $ atomic vector bug in Sensor Reading summary

### PR DESCRIPTION
**Pull request by dpattermann-usgs**
Fixed $ atomic vector bug in Sensor reading summary. It was the same bug as Site visit peaks. I modified them to use the same check.

### CODE REVIEW

**Comment by jordansread** [comment]
merging while in progress https://travis-ci.org/USGS-R/repgen/builds/94942675 ? :cry:

**Comment by thongsav-usgs** [comment]
desperate times, desperate measures @jread-usgs

**Comment by dpattermann-usgs** [comment]
Oh shoot, my bad. Sorry! Looks like it passed though.

**Comment by jordansread** [comment]
I get it. It's Friday. :tada:

**Pull request merged**
