### PR TITLE
AQCU-1196: TSS: Make Column headings sortable

### PR DESCRIPTION
**Pull request by zmoore-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
This works really well right after I render it in the browser, but after the files are saved locally, it doesn't seem to work anymore. It does retain the sort that you set before saving, though. That could be an improvement task since it's not explicitly called out in acceptance criteria. Not sure how hard that would be to handle?

**Review by mhines-usgs — APPROVED** [review]

**Comment by zmoore-usgs** [comment]
Hmm I'll look a little bit into having it work after saving it

**Comment by zmoore-usgs** [comment]
@mhines-usgs ^ That should hopefully fix the issue

**Comment by mhines-usgs** [comment]
checking it out now!

**Comment by mhines-usgs** [comment]
Excellent! :shipit:

**Comment by mhines-usgs** [comment]
One other observation related to usability is that it's not immediately obvious that the columns are sortable until you click on them. Not sure that's changeable with the theme, though.

**Comment by zmoore-usgs** [comment]
Yeah I've been messing around with that a bit to see if I can come up with something that implies they are sortable without implying any ordering since initially everything is sorted by start date and I don't want to imply that the other columns are ordered somehow. 

I think if I can set start date as the default selected/sorted column that might help, though it wouldn't necessarily imply that any other column but start date is sortable.

**Comment by zmoore-usgs** [comment]
If I could get something similar to this icon that might work: http://fontawesome.io/icon/sort/

**Comment by mhines-usgs** [comment]
Yeah, that would be perfect, if you can figure out how to get it to display. :/

**Comment by mhines-usgs** [comment]
Looks great @zmoore-usgs !

**Pull request merged**
