### PR TITLE
UV hydro refactor + log/linear logic + gsplot version 0.2.3

### PR DESCRIPTION
**Pull request by lindsayplatt**
Still to look at:
- effective shift vs measured shift (secondary plot); `effect_shift` currently skipped
- ylim values for `series_appr` set to 0 for now -- might be able to use limits call in new gsplot iterative builder workflow
- some y-values have character in the JSON (e.g. `water_qual` from pH-example data and `gw_level` from groundwater data); currently fixed by `as.numeric()` in `createPrimaryPlot`/`createSecondaryPlot` calls
- gsplot legend issue with missing cex values; therefore, added `cex=1` (the default) where it wasn't present for points calls

### CODE REVIEW

**Comment by lindsayplatt** [comment]
*\* don't merge this yet -- testthat is failing on my local machine

**Comment by lindsayplatt** [comment]
still failing tests, but only on extremes and vdiagram (which it must have been doing from changes before?)

``` r
 OK: 8 SKIPPED: 0 FAILED: 2
  1. Error: example data extremes 
  2. Error: example data vdiagram 
```

**Comment by thongsav-usgs** [comment]
Yes, these were likely already failing, but that was due to me assuming the CI builds here were expected to fail. We should clear this all up before releasing.

**Comment by thongsav-usgs** [comment]
Scratch that last comment... Appveyor is expected to fail, but travis-ci DID pass last time around.

See: https://github.com/USGS-R/repgen/pull/123

**Comment by lindsayplatt** [comment]
I hadn't touched extremes or vdiagram though :(

**Comment by lindsayplatt** [comment]
also, mine shows that it is still trying to build travis-ci for that PR

**Comment by thongsav-usgs** [comment]
Ah, you'd be correct. It's like that on a lot of PRs... hmmm, I think it's safe to assume they were already broken.

**Comment by lindsayplatt** [comment]
extremes and vdiagram still render correctly -- going to go ahead and merge

**Pull request merged**
