### PR TITLE
AQCU-1136: Fix for erroring/plotting on dvhydro when empty l…

### PR DESCRIPTION
**Pull request by mhines-usgs**
…ist elements are sent to plotItem function. Introduced with the est/stat edges work done a few weeks ago.

### CODE REVIEW

**Review by zmoore-usgs — APPROVED** [review]
Seems like a good fix to me, though not 100% sure if this would have any unintended side-effects or not. I think @lindsaycarr is pretty busy right now so it's probably okay to go ahead and merge but might be a good idea to have her look at this at some point, just to be safe.

**Comment by mhines-usgs** [comment]
Thanks, will do!

**Comment by lindsayplatt** [comment]
Added it to my list for Friday!

**Comment by mhines-usgs** [comment]
@lindsaycarr nice, thank you, wasn't sure if I should make an issue or just ask in standup, so THANKS! :pray:

**Review by lindsayplatt — COMMENTED** [review]
It seems like it would be a good idea to add some tests for this so it doesn't pop up again. I'm going to make a few and do a PR soon.

**Comment by lindsayplatt** [comment]
I'm starting to think that we need a slightly different approach. If `item` has any empty fields, it might cause an error downstream since fields in `item` are describing the actual plotting info like x and y values. If those are missing, it could balk somewhere else, right? Should we be skipping an item entirely if it has empty fields?

@mhines-usgs @zmoore-usgs

**Comment by mhines-usgs** [comment]
thanks @lindsaycarr !!

**Pull request merged**
