### PR TITLE
truncating labels for uvhydro & vdiagram round 2

### PR DESCRIPTION
**Pull request by lindsayplatt**
updated how `width_char` is calculated. Example illustrating truncated labels from @thongsav-usgs  was because it thought that the label was getting cutoff on the right axis b/c the character width used was enormous, so it rotated the callout. Since it was near the left axis, it was truncated from the left. 

Example from PT: https://cida-eros-aqcudev.er.usgs.gov:8443/aqcu-front-end/service/reports/vdiagram/?primaryTimeseriesIdentifier=209c5e8130244dcc995a0b1321cd74eb&upchainTimeseriesIdentifier=925c02693cc247b4a00ac0d605ce4fc0&ratingModelIdentifier=Gage+height-Discharge.STGQ%4006934500&station=06934500&lastMonths=12

### CODE REVIEW

**Comment by lindsayplatt** [comment]
once checks pass this should be good to merge

**Comment by thongsav-usgs** [comment]
:+1:

**Comment by thongsav-usgs** [comment]
Looks like test coverage went down slightly.

**Comment by lindsayplatt** [comment]
wow...0.2% and it throws a red X

**Pull request merged**
