### PR TITLE
Revert "starting on rating diagram"

### PR DESCRIPTION
**Pull request by thongsav-usgs**
Reverts USGS-R/repgen#63

### CODE REVIEW

**Comment by jordansread** [comment]
ugg https://travis-ci.org/USGS-R/repgen/builds/66932446#L1206

**Comment by jordansread** [comment]
do you have to yank out the ratings work? Shouldn't conflict w/ UV

**Comment by thongsav-usgs** [comment]
There was a commit that tried to pull out some generic plotting that has thrown off the ylims. It also appears the GW and QW plotting was lost somehow. 

We don't have to yank it out, but keeping it in reduces the amount of demo-able material.

**Comment by thongsav-usgs** [comment]
let me take a look at this tomorrow. rather than yank everything out, I should probably just selectively revert UV hydro.

**Pull request merged**
