### PR TITLE
AQCU-1183: DC: Make legend dynamic?

### PR DESCRIPTION
**Pull request by zmoore-usgs**

### CODE REVIEW

**Review by thongsav-usgs — APPROVED** [review]

**Comment by mhines-usgs** [comment]
That is pretty awesome! :+1:

**Review by mhines-usgs — APPROVED** [review]

**Comment by mhines-usgs** [comment]
Hm, except that I see stat derived showing up twice for some reason? 
image

**Comment by zmoore-usgs** [comment]
Hmm I'll take a look at that. What TS / Site is that report for?

**Comment by mhines-usgs** [comment]
site 02444160, discharge!

**Comment by zmoore-usgs** [comment]
Just pushed a fix

**Comment by mhines-usgs** [comment]
Grabbing again to check it out!

**Comment by mhines-usgs** [comment]
Looks good!!

**Pull request merged**
