### PR TITLE
AQCU-1131: For a start or end date that is open-ended....

### PR DESCRIPTION
**Pull request by zmoore-usgs**
....list "Open" versus 9999-MM-DD or 0000-MM-DD

### CODE REVIEW

**Comment by mhines-usgs** [comment]
checking this out now @zmoore-usgs

**Comment by mhines-usgs** [comment]
This seems to work great for all the example files; but I do see some errors appearing in my console using them at times related to missing data. 
```
3: In value[[3L]](cond) :
  Returning list() for TSS Rating Curves. Error: Error in validateFetchedData(curves, "Rating Curves", requiredFields, : Data for: ' Rating Curves ' was not found in report JSON.

4: In value[[3L]](cond) :
  Returning list() for TSS Rating Shifts. Error: Error in validateFetchedData(shifts, "Rating Shifts", requiredFields, : Data for: ' Rating Shifts ' was not found in report JSON.
```

and I think the same comes up in an error on the Check function in Rstudio
```
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  1. Failure: parseTSSQualifiers properly retrieves the qualifiers (@test-timeseriessummary.R#121) 
  2. Failure: parseTSSQualifiers properly retrieves the qualifiers (@test-timeseriessummary.R#122) 
  3. Failure: parseTSSNotes properly retrieves the notes (@test-timeseriessummary.R#147) 
  4. Failure: parseTSSNotes properly retrieves the notes (@test-timeseriessummary.R#148) 
  5. Failure: parseTSSGrades properly retrieves the grades (@test-timeseriessummary.R#172) 
  6. Failure: parseTSSGrades properly retrieves the grades (@test-timeseriessummary.R#173) 
  7. Failure: readRatingCurves properly retrieves the rating cruves (@test-timeseriessummary.R#253) 
  8. Failure: readRatingCurves properly retrieves the rating cruves (@test-timeseriessummary.R#255) 
  9. Failure: readRatingCurves properly retrieves the rating cruves (@test-timeseriessummary.R#256) 
```

also looks like some mixups of reportData versus reportObject in the documentation for functions versus what is used in the function arguments. fyi

**Comment by zmoore-usgs** [comment]
The things you're seeing in the console should just be warnings and not errors. 

The errors in the check are actual test failures that I also just noticed (most of them are years that were 9999 or 0000 and are now "Open") and am fixing now

**Comment by mhines-usgs** [comment]
:+1:

**Review by mhines-usgs — APPROVED** [review]

**Pull request merged**
