### PR TITLE
AQCU-1155: adding fixed width columns for tables in the UVHydro report

### PR DESCRIPTION
**Pull request by mhines-usgs**

### CODE REVIEW

**Comment by mhines-usgs** [comment]
**BEFORE:**
image


**AFTER:**
image

**Comment by mwernimont** [comment]
@mhines-usgs I have no approval abilities since no access rights, but that CSS looks good to me, and the table looks great all lined up. 👍

**Comment by mhines-usgs** [comment]
thanks @mwernimont - hopefully pt got you some rights now. I'll still wait for travis to finish before merging.

**Review by mwernimont — APPROVED** [review]

**Comment by mwernimont** [comment]
Pssh, look at those rights in use. THE POWER!!

**Pull request merged**
