### PR TITLE
label stacking on uvhydro fixed + header for vdiagram/extremes

### PR DESCRIPTION
**Pull request by lindsayplatt**
For UV hydrograph, the labels for comments on the secondary plot will not cover each other when the dates are within one day. 

Standardized header for vdiagram. 

Header added to extremes similar to vdiagram (image, author, date created) but includes additional information.

### CODE REVIEW

**Comment by mhines-usgs** [comment]
Nice! @lindsaycarr -- The label stacking looks awesome! :)

I think you'll end up having a conflict when you try to merge this. The missing bits are the changes to outline the points on the graph and the style change for the points. Have you resolved conflicts before in git?

**Comment by lindsayplatt** [comment]
Thanks!

I have resolved conflicts, but I forget exactly how. I can merge this pull request and then slack msg you if I have an issue?

**Comment by mhines-usgs** [comment]
@lindsaycarr sounds good. cool.

**Comment by lindsayplatt** [comment]
Didn't seem to have any merging issues!

**Pull request merged**
