### PR TITLE
AQCU-1199: modifying the format of grades AND NOTES before merging with qualifi…

### PR DESCRIPTION
**Pull request by mhines-usgs**
…ers because there was a column mismatch

### CODE REVIEW

**Comment by zmoore-usgs** [comment]
Pulling this down to test now

**Comment by mhines-usgs** [comment]
Thanks @zmoore-usgs I just noticed the test failure, and will check that out in a minute.

**Review by zmoore-usgs — APPROVED** [review]
Tested locally and it works well for me! Guessing the test failure is just needing to replace "code" with "value" in the test cases. Once that is passing I think this is good to go!

**Comment by mhines-usgs** [comment]
@zmoore-usgs yep, just pushed that up! :D thanks for reviewing.

**Comment by zmoore-usgs** [comment]
Just found a small issue, not sure if it's related to this ticket or not. Testing with timeseriessummary-example2.json it seems the note row in the metadata section is a bit malformed? Could just be bad test data though.

image

**Comment by mhines-usgs** [comment]
Thanks, I am grabbing the JSON she sent in with her problem too to verify, and will check that out too.

**Comment by mhines-usgs** [comment]
Is that a qualifier? (Note) or something different? Might also have to adjust notes...
Yeah I think it's probably the same issue, I can fix it while I'm in here..

**Comment by zmoore-usgs** [comment]
Notes are their own thing separate from qualifiers and grades I believe.

**Pull request merged**
