### PR TITLE
uvhydro: chart raw values to corrected

### PR DESCRIPTION
**Pull request by lindsayplatt**
AQCU-736

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@mhines-usgs this passed checks locally. Is there any way to kick off another build without committing something? I feel like it failed because of network issues?

**Comment by mhines-usgs** [comment]
yes, I can try through Travis! one sec.

**Comment by mhines-usgs** [comment]
yeah, if you "sign in" to Travis (with your github username/password) you'll see a little redo/refresh icon on the upper right side, I just hit that and it started again. Another way, without signing in, is to close and re-open the pull request. 

untitled

**Comment by lindsayplatt** [comment]
oh awesome, thanks! I'll probably just try that close/reopen method next time - way less effort haha

**Comment by mhines-usgs** [comment]
I think the sig for uvhydro needs to be updated to include dplyr

**Comment by lindsayplatt** [comment]
yep just committed that

On Mon, Jun 6, 2016 at 12:54 PM, Megan Hines notifications@github.com
wrote:

> I think the sig for uvhydro needs to be updated to include dplyr
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/USGS-R/repgen/pull/351#issuecomment-224036090, or mute
> the thread
> https://github.com/notifications/unsubscribe/AMm8LoHAWLcssco5ylBDSwK4wA7qqCMgks5qJF7jgaJpZM4IvDLB
> .

## 

_Lindsay R. Carr_
Contractor, Lynxnet LLC
Office of Water Information | U.S. Geological Survey
(608) 821-3837 | lcarr@usgs.gov | _cida.usgs.gov/datascience
http://cida.usgs.gov/datascience.html_

**Pull request merged**
