### PR TITLE
fixes for pandoc error 43 as suggested by Lindsay. Removing the inter…

### PR DESCRIPTION
**Pull request by mhines-usgs**
…mediates_dir=output_dir.

### CODE REVIEW

**Comment by lindsayplatt** [comment]
So did this actually fix it for you?

**Comment by mhines-usgs** [comment]
@lindsaycarr yes!

**Comment by lindsayplatt** [comment]
fantastic!

**Comment by jordansread** [comment]
hmm, but why was it being used in the first place? Wasn't that added by mike or @thongsav-usgs ?

**Comment by thongsav-usgs** [comment]
Yeah, added by mike https://github.com/USGS-R/repgen/commit/7b8a5dbfe16398873ebae9ae63b54a3d3e974239

Doesn't say why...

**Comment by thongsav-usgs** [comment]
:shipit:

**Comment by lindsayplatt** [comment]
https://github.com/rstudio/rmarkdown/issues/130 

"intermediate and output directories are relative to the input path, not the working directory." 

So maybe that is why defining our intermediate directory caused it to choke? I am not really finding anything about why it would be necessary to define the intermediate path

**Pull request merged**
