### PR TITLE
Modifying hyperlinks to open in new tabs in the browser

### PR DESCRIPTION
**Pull request by mhines-usgs**
https://internal.cida.usgs.gov/jira/browse/AQCU-771

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@mhines-usgs is there a specific reason why the sims url for uvhydro is changed in uvhydrograph-data, but it's changed in the markdown file for dvhydrograph and fiveyrgwsum?

**Comment by mhines-usgs** [comment]
I honestly don't know, just changed what was there, eg uvhydro had the function in data instead of just reading in to the Rmd directly. Should I make uvhydro like the others instead to be consistent?

**Comment by lindsayplatt** [comment]
I think that would probably be the best way to handle it. Or make a function? That way you can keep uvhydro's check for NULL urls and use it for dvhydro and fiveyr

**Comment by mhines-usgs** [comment]
Ok, so make a function in utils-shared?

**Comment by lindsayplatt** [comment]
:+1:

**Pull request merged**
